Repository Team-PandaN/Team-PandaN-Back, pull requests merged in 2021-08, with the labels that each got.

#46 Note 조회, 생성, 삭제 시 예외처리
  src/main/java/com/example/teampandanback/domain/note/NoteRepository.java
  src/main/java/com/example/teampandanback/dto/note/response/NoteOfProjectResponseDto.java
  src/main/java/com/example/teampandanback/service/NoteService.java
Labels: Refactoring :recycle:, 예외 처리 :see_no_evil:

#71 [기능 구현] 노트 조회와 노트 삭제 시 북마크 삭제
  src/main/java/com/example/teampandanback/controller/NoteController.java
  src/main/java/com/example/teampandanback/domain/bookmark/BookmarkRepositoryImpl.java
  src/main/java/com/example/teampandanback/domain/bookmark/BookmarkRepositoryQuerydsl.java
  src/main/java/com/example/teampandanback/domain/note/NoteRepositoryImpl.java
  src/main/java/com/example/teampandanback/domain/note/NoteRepositoryQuerydsl.java
  src/main/java/com/example/teampandanback/dto/note/response/NoteEachMineInTotalResponseDto.java
  src/main/java/com/example/teampandanback/dto/note/response/NoteMineInTotalResponseDto.java
  src/main/java/com/example/teampandanback/service/NoteService.java
Labels: 2차

#80 [기능 구현] 댓글 수정
  src/main/java/com/example/teampandanback/controller/CommentController.java
  src/main/java/com/example/teampandanback/domain/Comment/Comment.java
  src/main/java/com/example/teampandanback/dto/comment/response/CommentUpdateResponseDto.java
  src/main/java/com/example/teampandanback/dto/project/ProjectDetailResponseDto.java
  src/main/java/com/example/teampandanback/service/CommentService.java
Labels: 3차

#105 [Refactoring] 프로젝트 목록 조회 쿼리 개선
  src/main/java/com/example/teampandanback/domain/bookmark/BookmarkRepositoryImpl.java
  src/main/java/com/example/teampandanback/domain/bookmark/BookmarkRepositoryQuerydsl.java
  src/main/java/com/example/teampandanback/domain/note/NoteRepositoryQuerydsl.java
  src/main/java/com/example/teampandanback/domain/project/ProjectRepository.java
  src/main/java/com/example/teampandanback/domain/project/ProjectRepositoryImpl.java
  src/main/java/com/example/teampandanback/domain/project/ProjectRepositoryQuerydsl.java
  src/main/java/com/example/teampandanback/domain/user_project_mapping/UserProjectMappingRepositoryImpl.java
  src/main/java/com/example/teampandanback/domain/user_project_mapping/UserProjectMappingRepositoryQuerydsl.java
  src/main/java/com/example/teampandanback/dto/bookmark/response/BookmarkDetailForProjectListDto.java
  src/main/java/com/example/teampandanback/dto/project/response/ProjectDetailForProjectListDto.java
  src/main/java/com/example/teampandanback/dto/project/response/ProjectEachResponseDTO.java
  src/main/java/com/example/teampandanback/dto/project/response/ProjectEachResponseDto.java
  src/main/java/com/example/teampandanback/dto/project/response/ProjectListResponseDto.java
  src/main/java/com/example/teampandanback/dto/user/CrewDetailForProjectListDto.java
  src/main/java/com/example/teampandanback/service/ProjectService.java
Labels: Refactoring :recycle:

#106 feat: 파일 MVP 구현 및 북마크 한 파일 조회 수정
  src/main/java/com/example/teampandanback/controller/FileController.java
  src/main/java/com/example/teampandanback/controller/NoteController.java
  src/main/java/com/example/teampandanback/domain/bookmark/BookmarkRepositoryImpl.java
  src/main/java/com/example/teampandanback/domain/file/File.java
  src/main/java/com/example/teampandanback/domain/file/FileRepository.java
  src/main/java/com/example/teampandanback/domain/file/FileRepositoryImpl.java
  src/main/java/com/example/teampandanback/domain/file/FileRepositoryQuerydsl.java
  src/main/java/com/example/teampandanback/domain/note/NoteRepositoryImpl.java
  src/main/java/com/example/teampandanback/domain/user_project_mapping/UserProjectMappingRepository.java
  src/main/java/com/example/teampandanback/dto/file/request/FileDetailRequestDto.java
  src/main/java/com/example/teampandanback/dto/file/response/FileDeleteResponseDto.java
  src/main/java/com/example/teampandanback/dto/file/response/FileDetailResponseDto.java
  src/main/java/com/example/teampandanback/dto/note/request/NoteCreateRequestDto.java
  src/main/java/com/example/teampandanback/dto/note/request/NoteUpdateRequestDto.java
  src/main/java/com/example/teampandanback/dto/note/response/NoteCreateResponseDto.java
  src/main/java/com/example/teampandanback/dto/note/response/NoteDetailResponseDto.java
  src/main/java/com/example/teampandanback/dto/note/response/NoteEachBookmarkedResponseDto.java
  src/main/java/com/example/teampandanback/dto/note/response/NoteUpdateResponseDto.java
  src/main/java/com/example/teampandanback/service/FileService.java
  src/main/java/com/example/teampandanback/service/NoteService.java
  src/main/java/com/example/teampandanback/service/ProjectService.java
  src/main/java/com/example/teampandanback/testData/testDataRunner.java
  src/main/java/com/example/teampandanback/utils/PandanUtils.java
Labels: MVP :sparkles:, Refactoring :recycle:

#108 프로젝트 탈퇴 기능 구현
  src/main/java/com/example/teampandanback/controller/ProjectController.java
  src/main/java/com/example/teampandanback/domain/bookmark/BookmarkRepositoryImpl.java
  src/main/java/com/example/teampandanback/domain/bookmark/BookmarkRepositoryQuerydsl.java
  src/main/java/com/example/teampandanback/domain/note/NoteRepositoryImpl.java
  src/main/java/com/example/teampandanback/domain/note/NoteRepositoryQuerydsl.java
  src/main/java/com/example/teampandanback/domain/user_project_mapping/UserProjectMappingRepositoryImpl.java
  src/main/java/com/example/teampandanback/domain/user_project_mapping/UserProjectMappingRepositoryQuerydsl.java
  src/main/java/com/example/teampandanback/dto/project/response/ProjectLeaveResponseDto.java
  src/main/java/com/example/teampandanback/service/NoteService.java
  src/main/java/com/example/teampandanback/service/ProjectService.java
Labels: 3차, Feature

#110 유저가 참여하지 않은 프로젝트의 노트 RUD관련 예외처리
  src/main/java/com/example/teampandanback/controller/NoteController.java
  src/main/java/com/example/teampandanback/domain/note/NoteRepositoryImpl.java
  src/main/java/com/example/teampandanback/domain/note/NoteRepositoryQuerydsl.java
  src/main/java/com/example/teampandanback/dto/note/request/NoteCreateRequestDto.java
  src/main/java/com/example/teampandanback/service/NoteService.java
Labels: 예외 처리 :see_no_evil:

#130 Jenkinsfile로 파이프라인 실행방법 변경
  Jenkinsfile.groovy
Labels: ENH :hammer_and_wrench:
